### ISSUE TITLE
Poor visibility of italics

### ISSUE THREAD

**Issue by TriniTDM** [Iniquitatis/DDLCComfyUI#10]
The font you swapped in makes it really hard to distinguish text that's italicized from plain text. I'm using the Mint theme if that makes any difference. To demonstrate the issue, I'm attaching a screenshot. The word "that" is italicized here, but you can barely tell. 
![screenshot0001](https://user-images.githubusercontent.com/52469676/100395774-331bc500-3010-11eb-9acd-ba9e824dc75b.png)

**Comment by Iniquitatis** [comment]
Unfortunately, there's nothing I can do without modifying the font file itself.

_Picking another font is out of question. I've tried literally hundreds of typefaces until an appropriate one was found. So, I guess, that italic font is still a good compromise._
