### ISSUE TITLE
No file or directory error

### ISSUE THREAD

**Issue by ChloeRaven** [Iniquitatis/DDLCComfyUI#21]
Just updated Monika After Story to 0.12.3, and now i getting this error that the game can't find a directory or file, sometimes its the 'comfy_meta' or the file 'logfile'.
Don't know if it's just a bug because of the new update, but i would be grateful if this error could be resolved or the script updated, or if there's something i can do. That's a great submod

**Comment by Iniquitatis** [comment]
Works perfectly fine for me on the latest MAS version.
Are you sure you installed the mod [properly](https://github.com/Iniquitatis/DDLCComfyUI#installation)?
